[package]
edition = "2021"
name = "solvurus_engine"
version = "0.0.0"

[lib]
crate-type = ["lib"]

[dependencies]
pest = "2.6"
pest_derive = "2.6"
lazy_static = "1.4.0"
thiserror = "1.0.44"
anyhow = "1.0.72"
