name: CI

on: [push, pull_request, ]

jobs:
  coverage:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Test Action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview
          override: true

      - uses: Swatinem/rust-cache@v1
      
      - uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: coverage